config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following,  :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, only: %i(new create edit update)
  resources :microposts, onlys: %i(create destroy)
  resources :relationships, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".help"), help_path %></li>
      <li><%= link_to t(".ruby_on_rails"), Settings.rails_host.ruby_on_rails %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="nav navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".app_name"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.title"), root_path %><li>
        <li><%= link_to t("static_pages.help.title"), help_path %><li>
        <% if logged_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li class="dropdown">
            <%= link_to raw(t(".account")+"<b class='caret'></b>".html_safe),
             "#", { "data-toggle" => "dropdown" } %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t(".logout"), logout_path, method: :delete,
               data: { confirm: t(".you_sure") } %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %><li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>